API_KEY = 'Get your own One Call API key'
API_CALL_COUNT_FOLDER = './daliy_api_call_counts'
API_CALL_COUNT_LIMIT = 1000
BSU_LATITUDE = 39.017701
BSU_LONGITUDE = -76.759879
UNIT_SYSTEM_TYPE = 'metric'
HIST_DAYS = 0
HIST_WEEKS = 2
HIST_LOG_FOLDER = './historical_logs'
ROUND_LENGTH = 150
ROUND_DELAY_SEC = 80
HIST_DATA_FOLDER = './historical_csvs'
TRAINING_OUTPUT_FOLDER = './training_outputs'
TRAINING_OUTPUT_CHOICE = ''
